repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.4.0
    hooks:
      - id: check-yaml
      - id: end-of-file-fixer
      - id: trailing-whitespace
      - id: name-tests-test
        args: ["--pytest-test-first"]
  - repo: https://github.com/psf/black
    rev: 23.1.0
    hooks:
      - id: black
        language_version: python3.10
  # - repo: https://github.com/pycqa/isort
  #   rev: 5.12.0
  #   hooks:
  #     - id: isort
  #       name: isort (python)
  - repo: https://github.com/pycqa/flake8
    rev: 6.0.0
    hooks:
      - id: flake8
        # TODO: Look for a better precommit hook for flake8/black integration
        # Ignore:
        #   - E501: Line too long (Reason: will be done by Black instead)
        #   - W503: line break (Reason: will be done by black instead)
        args: ["--ignore=E501,W503"]
  - repo: https://github.com/nbQA-dev/nbQA
    rev: 1.6.1
    hooks:
      - id: nbqa-black
      - id: nbqa-pyupgrade
        args: ["--py37-plus"]
      - id: nbqa-isort
        args: ["--float-to-top"]
  - repo: https://github.com/python-poetry/poetry
    rev: 1.3.2
    hooks:
      - id: poetry-check
      - id: poetry-lock
      - id: poetry-export
        args: ["--without-hashes", "--format", "requirements.txt", "--output", "requirements.txt"]
